export enum ImageType {
    USER_COVER_IMAGE = "USER_COVER_IMAGE",
    USER_AVATAR_IMAGE = "USER_AVATAR_IMAGE",
    CATALOG_COVER_IMAGE = "CATALOG_COVER_IMAGE",
    PACKAGE_COVER_IMAGE = "PACKAGE_COVER_IMAGE",
    COLLECTION_COVER_IMAGE = "COLLECTION_COVER_IMAGE"
}
