# Reference: https://prettier.io/docs/en/options.html

tabWidth: 4
useTabs: false
printWidth: 120

trailingComma: none
bracketSpacing: true
jsxBracketSameLine: true

semi: true
arrowParens: always
singleQuote: false
