export JWT_AUDIENCE="localhost"
export JWT_ISSUER="localhost"
export JWT_KEY="abc123"
export NODE_MODULES_DIRECTORY="node_modules"
export APOLLO_KEY="service:family-connections:asdfasdfasdfasdf"
export APOLLO_GRAPH_VARIANT="dev"
export GCLOUD_STORAGE_BUCKET_NAME="media"
export GOOGLE_CLOUD_PROJECT="adsfasdf"
export GRAPHQL_CONTEXT_USER_SUB="auth0|adsfasdfasdfasdf"
export FILESYSTEM_STORAGE_DIRECTORY="local_storage"
export MIXPANEL_TOKEN="asdfasdfasdf"
export TYPEORM_PORT="5432"
export TYPEORM_DATABASE="postgres"
export TYPEORM_SCHEMA="public"
export TYPEORM_USERNAME="postgres"
export TYPEORM_PASSWORD="postgres"
export SENDGRID_API_KEY="asdfasdfa"

export GOOGLE_LOGIN_CLIENT_ID="832769547626-tnldssk3ljco2icmss266tnn5epalheb.apps.googleusercontent.com"
export GOOGLE_LOGIN_SECRET="p1YiHnsuBMHcyltiWL_1h5yt"

export REGISTRY_HOSTNAME="localhost"
export REGISTRY_PORT="4000"