export REGISTRY_URL="http://localhost:4000"
export REGISTRY_NAME="DataPM Local Development"
export REGISTRY_HOSTNAME="localhost"
export REGISTRY_PORT="4000"
export JWT_AUDIENCE="localhost"
export JWT_ISSUER="localhost"
export JWT_KEY="!!!!REPLACE_ME!!!"
export NODE_MODULES_DIRECTORY="node_modules"
export APOLLO_KEY="service:family-connections:asdfasdfasdfasdf"
export APOLLO_GRAPH_VARIANT="dev"
export GCLOUD_STORAGE_BUCKET_NAME="media"
export GOOGLE_CLOUD_PROJECT="adsfasdf"
export FILESYSTEM_STORAGE_DIRECTORY="local_storage"
export MIXPANEL_TOKEN="asdfasdfasdf"
export TYPEORM_PORT=${TYPEORM_PORT:=5432}
export TYPEORM_DATABASE="datapm"
export TYPEORM_SCHEMA="public"
export TYPEORM_USERNAME="postgres"
export TYPEORM_PASSWORD="postgres"
export REQUIRE_EMAIL_VERIFICATION=${REQUIRE_EMAIL_VERIFICATION:=false}
# export SMTP_SERVER="smtp.sendgrid.net"
# export SMTP_PORT="465"
# export SMTP_USER="apikey"
# export SMTP_PASSWORD="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"
# export SMTP_FROM_NAME="Localhost DataPM Registry"
# export SMTP_FROM_ADDRESS="support@datapm.io"
# export SMTP_SECURE="true"