import { MigrationInterface, QueryRunner } from "typeorm";

export class CreatePackageIssuesTables1614024797915 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        const query = `
            CREATE TABLE IF NOT EXISTS public."package_issue" (
                id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
                issue_number INTEGER NOT NULL,
                package_id INTEGER NOT NULL REFERENCES public."package" (id) ON DELETE CASCADE,
                author_id INTEGER NOT NULL REFERENCES public."user" (id) ON DELETE CASCADE,
                subject VARCHAR NOT NULL,
                content VARCHAR NOT NULL,
                status VARCHAR NOT NULL DEFAULT 'OPEN',
                created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
            );


            CREATE INDEX ON package_issue(package_id);
            CREATE INDEX ON package_issue(status);

            ----------------------------------------------------------------------------------------

            CREATE TABLE IF NOT EXISTS public."issue_comment" (
                id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
                comment_number INTEGER NOT NULL,
                issue_id INTEGER NOT NULL REFERENCES public."package_issue" (id) ON DELETE CASCADE,
                author_id INTEGER NOT NULL REFERENCES public."user" (id) ON DELETE CASCADE,
                content VARCHAR NOT NULL,
                created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
            );
            

            CREATE INDEX ON issue_comment(issue_id);

        `;

        queryRunner.query(query);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // no-op
    }
}
