import { MigrationInterface, QueryRunner } from "typeorm";

export class CreatePackageVersionsDiffTables1616091117502 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        const query = `
            CREATE TABLE IF NOT EXISTS version_comparison (
            id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
            new_version_id INTEGER NOT NULL REFERENCES version (id) ON DELETE CASCADE,
            old_version_id INTEGER NOT NULL REFERENCES version (id) ON DELETE CASCADE,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );

        CREATE UNIQUE INDEX IF NOT EXISTS version_comparison_versions_index ON version_comparison (new_version_id, old_version_id);

        CREATE TABLE IF NOT EXISTS version_difference (
            id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
            version_comparison_id INTEGER NOT NULL REFERENCES version_comparison (id) ON DELETE CASCADE,
            type VARCHAR,
            pointer VARCHAR
        );

        CREATE INDEX IF NOT EXISTS version_difference_version_comparison_index ON version_difference (version_comparison_id);`;

        return queryRunner.query(query);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // no-op
    }
}
