import { MigrationInterface, QueryRunner } from "typeorm";

export class CreatePlatformSettingsTable1618864385071 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        return queryRunner.query(`
            DROP SEQUENCE IF EXISTS platform_settings_id_seq;
            CREATE TABLE IF NOT EXISTS platform_settings (
                id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
                key VARCHAR NOT NULL UNIQUE,
                serialized_settings VARCHAR,
                is_public BOOLEAN DEFAULT FALSE,
                created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
            );
            CREATE UNIQUE INDEX IF NOT EXISTS platform_settings_key_index ON platform_settings (key);
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // no-op
    }
}
