import { MigrationInterface, QueryRunner } from "typeorm";

const sql = `

    ALTER TABLE activity_log ADD column "removed_item_name"  text;
    ALTER TABLE activity_log ADD column "removed_item_id"  bigint;

    ALTER TYPE activity_log_event_type_enum ADD VALUE 'CATALOG_PACKAGE_ADDED';
    ALTER TYPE activity_log_event_type_enum ADD VALUE 'CATALOG_PACKAGE_REMOVED';
    ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_ISSUE_CREATED';
    ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_ISSUE_COMMENT_CREATED';
    ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_ISSUE_COMMENT_EDIT';
    ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_ISSUE_COMMENT_DELETED';
    ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_ISSUE_CLOSED';
    ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_ISSUE_DELETED';
    ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_MAJOR_CHANGE';
    ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_MINOR_CHANGE';
    ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_PATCH_CHANGE';
    ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_ISSUE_EDIT';
    ALTER TYPE activity_log_event_type_enum ADD VALUE 'CATALOG_UNCLAIMED_CHANGED';
    ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_ISSUE_STAUS_CHANGE';

    COMMIT;

    alter table activity_log alter column event_type type activity_log_event_type_enum using event_type::activity_log_event_type_enum;


    delete from "activity_log" where target_package_version_id not in (select id from "version" v2 );

    delete from "activity_log" where target_package_issue_id not in (select id from package_issue v2 );
    
    ALTER TABLE "public"."activity_log" ADD CONSTRAINT activity_log_target_package_version_id_fkey FOREIGN KEY (target_package_version_id) REFERENCES "public"."version" (id) ON DELETE CASCADE;
    ALTER TABLE "public"."activity_log" ADD CONSTRAINT activity_log_target_package_issue_id_fkey FOREIGN KEY (target_package_issue_id) REFERENCES "public"."package_issue" (id) ON DELETE CASCADE;
    
    delete FROM "follow";
    ALTER TABLE "follow" DROP COLUMN event_types;
    ALTER TABLE "follow" ADD COLUMN event_types activity_log_event_type_enum[];



CREATE AGGREGATE array_accum (anyarray)
(
    sfunc = array_cat,
    stype = anyarray,
    initcond = '{}'
);  


DROP SEQUENCE IF EXISTS platform_state_id_seq;
CREATE TABLE IF NOT EXISTS platform_state (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    key VARCHAR NOT NULL UNIQUE,
    serialized_state VARCHAR,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS platform_state_key_index ON platform_state (key);

`;

export class NotificationTimestamps1622210412398 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        queryRunner.query(sql);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // no-op
    }
}
