import {MigrationInterface, QueryRunner} from "typeorm";

const sql = `

CREATE TABLE "public"."group" (
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    creator_id INTEGER NOT NULL REFERENCES public."user" (id) ON DELETE CASCADE,
    name VARCHAR(256) NOT NULL,
    slug VARCHAR(256) NOT NULL
);

CREATE TABLE "public"."group_user" (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER NOT NULL REFERENCES public."user" (id) ON DELETE CASCADE,
    group_id INTEGER NOT NULL REFERENCES public."group" (id) ON DELETE CASCADE,
    creator_id INTEGER NOT NULL REFERENCES public."user" (id) ON DELETE CASCADE,
    permissions public.user_package_permission_permission_enum[] NOT NULL
);

CREATE TABLE "public"."group_package_permissions" (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    package_id INTEGER NOT NULL REFERENCES public."package" (id) ON DELETE CASCADE,
    group_id INTEGER NOT NULL REFERENCES public."group" (id) ON DELETE CASCADE,
    creator_id INTEGER NOT NULL REFERENCES public."user" (id) ON DELETE CASCADE,
    permissions public.user_package_permission_permission_enum[] NOT NULL
);

CREATE TABLE "public"."group_catalog_permissions" (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    catalog_id INTEGER NOT NULL REFERENCES public."package" (id) ON DELETE CASCADE,
    group_id INTEGER NOT NULL REFERENCES public."group" (id) ON DELETE CASCADE,
    creator_id INTEGER NOT NULL REFERENCES public."user" (id) ON DELETE CASCADE,
    permissions public.user_catalog_permission_enum[] NOT NULL,
    package_permissions public.user_catalog_permission_enum[] NOT NULL

);


CREATE TYPE public.user_collection_permission_enum AS ENUM (
    'MANAGE',
    'VIEW',
    'EDIT',
    'NONE'
);

CREATE TABLE "public"."group_collection_permissions" (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    collection_id INTEGER NOT NULL REFERENCES public."package" (id) ON DELETE CASCADE,
    group_id INTEGER NOT NULL REFERENCES public."group" (id) ON DELETE CASCADE,
    creator_id INTEGER NOT NULL REFERENCES public."user" (id) ON DELETE CASCADE,
    permissions public.user_collection_permission_enum[] NOT NULL
);

ALTER TABLE public."credential" ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';
ALTER TABLE public."credential" ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE public."repository" ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';
ALTER TABLE public."repository" ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC';

ALTER TYPE activity_log_event_type_enum ADD VALUE 'COLLECTION_USER_PERMISSION_ADDED_UPDATED';
ALTER TYPE activity_log_event_type_enum ADD VALUE 'COLLECTION_GROUP_PERMISSION_ADDED_UPDATED';
ALTER TYPE activity_log_event_type_enum ADD VALUE 'COLLECTION_USER_PERMISSION_REMOVED';
ALTER TYPE activity_log_event_type_enum ADD VALUE 'COLLECTION_GROUP_PERMISSION_REMOVED';

ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_USER_PERMISSION_ADDED_UPDATED';
ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_GROUP_PERMISSION_ADDED_UPDATED';
ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_USER_PERMISSION_REMOVED';
ALTER TYPE activity_log_event_type_enum ADD VALUE 'PACKAGE_GROUP_PERMISSION_REMOVED';

ALTER TYPE activity_log_event_type_enum ADD VALUE 'CATALOG_USER_PERMISSION_ADDED_UPDATED';
ALTER TYPE activity_log_event_type_enum ADD VALUE 'CATALOG_GROUP_PERMISSION_ADDED_UPDATED';
ALTER TYPE activity_log_event_type_enum ADD VALUE 'CATALOG_USER_PERMISSION_REMOVED';
ALTER TYPE activity_log_event_type_enum ADD VALUE 'CATALOG_GROUP_PERMISSION_REMOVED';

`

export class Group1658499088645 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(sql);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
