export enum ActivityLogEventType {
    PACKAGE_PATCH_CHANGE = "PACKAGE_PATCH_CHANGE",
    PACKAGE_MINOR_CHANGE = "PACKAGE_MINOR_CHANGE",
    PACKAGE_MAJOR_CHANGE = "PACKAGE_MAJOR_CHANGE",
    PACKAGE_CREATED = "PACKAGE_CREATED",
    PACKAGE_DELETED = "PACKAGE_DELETED",
    PACKAGE_VIEWED = "PACKAGE_VIEWED",
    PACKAGE_FETCHED = "PACKAGE_FETCHED",
    COLLECTION_PACKAGE_ADDED = "COLLECTION_PACKAGE_ADDED",
    COLLECTION_PACKAGE_REMOVED = "COLLECTION_PACKAGE_REMOVED"
}
