export enum ActivityLogEventType {
    PACKAGE_CREATED = "PACKAGE_CREATED",
    PACKAGE_DELETED = "PACKAGE_DELETED",
    PACKAGE_VIEWED = "PACKAGE_VIEWED",
    PACKAGE_FETCHED = "PACKAGE_FETCHED",
    PACKAGE_PUBLIC_CHANGED = "PACKAGE_PUBLIC_CHANGED",
    PACKAGE_EDIT = "PACKAGE_EDIT",

    VERSION_CREATED = "VERSION_CREATED",
    VERSION_DELETED = "VERSION_DELETED",

    COLLECTION_CREATED = "COLLECTION_CREATED",
    COLLECTION_DELETED = "COLLECTION_DELETED",
    COLLECTION_EDIT = "COLLECTION_EDIT",
    COLLECTION_PACKAGE_ADDED = "COLLECTION_PACKAGE_ADDED",
    COLLECTION_PACKAGE_REMOVED = "COLLECTION_PACKAGE_REMOVED",
    COLLECTION_PUBLIC_CHANGED = "COLLECTION_PUBLIC_CHANGED",

    CATALOG_CREATED = "CATALOG_CREATED",
    CATALOG_DELETED = "CATALOG_DELETED",
    CATALOG_PUBLIC_CHANGED = "CATALOG_PUBLIC_CHANGED",
    CATALOG_EDIT = "CATALOG_EDIT",

    USER_CREATED = "USER_CREATED",
    USER_DELETED = "USER_DELETED",
    USER_EDIT = "USER_EDIT"
}

export enum ActivityLogChangeType {
    VERSION_FIRST_VERSION = "VERSION_FIRST_VERSION",
    VERSION_PATCH_CHANGE = "VERSION_PATCH_CHANGE",
    VERSION_MINOR_CHANGE = "VERSION_MINOR_CHANGE",
    VERSION_MAJOR_CHANGE = "VERSION_MAJOR_CHANGE",

    PUBLIC_ENABLED = "PUBLIC_ENABLED",
    PUBLIC_DISABLED = "PUBLIC_DISABLED",

    COVER_IMAGE_UPDATED = "COVER_IMAGE_UPDATED",
    COVER_IMAGE_REMOVED = "COVER_IMAGE_REMOVED",
    AVATAR_IMAGE_UPDATED = "AVATAR_IMAGE_UPDATED",
    AVATAR_IMAGE_REMOVED = "AVATAR_IMAGE_REMOVED"
}
