version: "3.7"

volumes:
  postgres_data_local: {}

services:
  postgres:
    image: postgres:11
    volumes:
      - type: volume
        source: postgres_data_local
        target: /var/lib/postgresql/data
        consistency: delegated
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=datapm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  datapm-registry:
    image: datapm-registry
    ports:
      - "4000:4000"
    env_file: 
      - Docker-env

