# This docker file builds the datapm/ci image, which is
# used by the GitHub action runners for the container image.

# Use the following commands to build the image and push it to docker hub
# docker buildx build --platform linux/amd64 -f Dockerfile-ci . -t datapm/ci:latest
# docker push datapm/ci:latest
FROM ubuntu:20.04
SHELL ["/bin/bash", "-c"]

# Get the latest package updates

RUN apt-get update

# Install build tools

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install --no-install-recommends --yes unzip g++ gcc make jq git-buildpackage rpm rpmlint curl docker-compose

RUN mkdir -p /usr/local/nvm

# Install NVM and then correct version of node

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 16.14.2
RUN curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | sh \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default
ENV NODE_PATH $NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

# Install Chromium for headless browser tests
# https://geekflare.com/install-chromium-ubuntu-centos/
RUN apt-get install --no-install-recommends --yes wget libappindicator1 fonts-liberation libasound2 libatk-bridge2.0-0 libatspi2.0-0 libdrm2 libgbm1 libgtk-3-0 libxkbcommon0 xdg-utils
RUN curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome.deb
RUN dpkg -i google-chrome.deb

# Install gcloud
# https://cloud.google.com/sdk/docs/install#deb
RUN apt-get install --no-install-recommends --yes apt-transport-https ca-certificates gnupg
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
RUN apt-get update && apt-get install --no-install-recommends --yes google-cloud-cli

# Install Terraform
# https://learn.hashicorp.com/tutorials/terraform/install-cli
RUN apt-get install --no-install-recommends --yes gnupg software-properties-common curl
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
RUN apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
RUN apt-get update && apt-get install --no-install-recommends --yes  terraform

# Install Python3
# Required for modules using node-gyp
RUN apt install --no-install-recommends --yes python3.9

CMD ["sh"]