directive @isAuthenticated on OBJECT | FIELD_DEFINITION
directive @validUsername on ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
directive @validUsernameOrEmailAddress on ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
directive @validPassword on ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
directive @validEmailAddress on ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION

enum AUTHENTICATION_ERROR {
    WRONG_CREDENTIALS
    EMAIL_ADDRESS_NOT_VERIFIED
    USER_NOT_FOUND
}

enum INVALID_USERNAME_ERROR {
    USERNAME_REQUIRED
    USERNAME_TOO_SHORT
    USERNAME_TOO_LONG
    INVALID_CHARACTERS
}

enum INVALID_PASSWORD_ERROR {
    PASSWORD_REQUIRED
    PASSWORD_TOO_SHORT
    PASSWORD_TOO_LONG
    INVALID_CHARACTERS
}
