type Group {
    slug: String!
    name: String
    users: [GroupUser!]
    createdAt: Date
    updatedAt: Date
    creator: User
}

type GroupUser {
    user: User
    group: Group
    permissions: [Permission!]
    createdAt: Date
    updatedAt: Date
    creator: User
}

type GroupPackagePermission {
    group: Group
    package: Package
    permissions: [Permission!]
    createdAt: Date
    updatedAt: Date
    creator: User
}

type GroupCatalogPermission {
    group: Group
    catalog: Catalog
    permissions: [Permission!]
    createdAt: Date
    updatedAt: Date
    creator: User
}

type GroupCollectionPermission {
    group: Group
    collection: Collection
    permissions: [Permission!]
    createdAt: Date
    updatedAt: Date
    creator: User
}
