directive @isAdmin on OBJECT | FIELD_DEFINITION
directive @isUserOrAdmin on OBJECT | FIELD_DEFINITION

"""
Represents one real world person, and their information
"""
type User {
    username: String!
    firstName: String
    lastName: String
    location: String
    twitterHandle: String
    description: String
    website: String
    emailAddress: String
    gitHubHandle: String
    nameIsPublic: Boolean
    locationIsPublic: Boolean
    twitterHandleIsPublic: Boolean
    gitHubHandleIsPublic: Boolean
    emailAddressIsPublic: Boolean
    websiteIsPublic: Boolean
    isAdmin: Boolean
}

"""
For creating an new user for other people as an administrator
"""
input CreateUserInputAdmin {
    firstName: String
    lastName: String
    emailAddress: String! @validEmailAddress
    username: String! @validUsername
    isAdmin: Boolean!
}

"""
For self service new user sign up
"""
input CreateUserInput {
    firstName: String
    lastName: String
    emailAddress: String! @validEmailAddress
    username: String! @validUsername
    password: String! @validPassword
}

"""
For updating a user's password
"""
input UpdateMyPasswordInput {
    oldPassword: String!
    newPassword: String! @validPassword
}

"""
For updating a user, or your own user. All values are optional, and only those specified are applied.
"""
input UpdateUserInput {
    username: String @validUsername
    firstName: String
    lastName: String
    emailAddress: String @validEmailAddress
    location: String
    description: String
    twitterHandle: String
    gitHubHandle: String
    website: String
    websiteIsPublic: Boolean
    nameIsPublic: Boolean
    locationIsPublic: Boolean
    twitterHandleIsPublic: Boolean
    gitHubHandleIsPublic: Boolean
    emailAddressIsPublic: Boolean
}
