#!/bin/bash

#Customize this for your application
APPLICATION_FILE_PATH=datapm

#Parameters
# IN THE FUTURE REPLACE x86_64 below with $(/usr/bin/uname -m) TO GET THE ARCHITECTURE
PRODUCT_HOME=/Library/__PRODUCT__/__VERSION__/x86_64

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

#Add application shortcut to /usr/local/bin
rm -f /usr/local/bin/datapm
ln -s ${PRODUCT_HOME}/${APPLICATION_FILE_PATH} /usr/local/bin/datapm
echo "Post installation process finished"
